
// GLCD defines
#define GLCD_CAMERA_WIDTH GLCD_WIDTH
#define GLCD_CAMERA_HEIGHT	GLCD_HEIGHT
#define GLCD_CAMERA_WIDTH_HALF GLCD_WIDTH * 0.5
#define GLCD_CAMERA_HEIGHT_HALF	GLCD_HEIGHT * 0.5
#define GLCD_CAMERA_EDGE_PADDING 5
#define GLCD_CHAR_WIDTH 16

// Message defines
#define CAMERA_SDCARD_PROMPT_MSG "INSERT SDCARD"
#define CAMERA_SDCARD_PROMPT_MSG_LEN 13

