#ifndef _CAMERA_GLOBALS_H
#define _CAMERA_GLOBALS_H

#define CAMERA_GLOBAL_DRAWON 1
#define CAMERA_GLOBAL_DRAWOFF 0

#define CAMERA_GLOBAL_DISPLAYBUFFER 0xC0000000


// DELETE
#define IMAGE_HEIGHT 48
#define IMAGE_WIDTH  48
//DELETE

#endif /* _CAMERA_GLOBALS_H */
